name: camera_android
publish_to: none
description: Android implementation of the camera plugin.
repository: https://github.com/flutter/packages/tree/main/packages/camera/camera_android
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+camera%22

version: 0.10.9+16

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

flutter:
  plugin:
    implements: camera
    platforms:
      android:
        package: io.flutter.plugins.camera
        pluginClass: CameraPlugin
        dartPluginClass: AndroidCamera

dependencies:
  camera_platform_interface: 
    git: https://github.com/kumsumit/camera_platform_interface.git
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: 
    git: https://github.com/kumsumit/flutter_plugin_android_lifecycle.git
  stream_transform: ^2.0.0

dev_dependencies:
  async: ^2.5.0
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  pigeon: ^22.4.1

topics:
  - camera
